In [2]:
import pandas as pd
# From dictionary
data = {'Name': ['Alice', 'Bob'], 'Age': [25, 30]}
df = pd.DataFrame(data)
print(df)

    Name  Age
0  Alice   25
1    Bob   30

In [3]:
# From list of lists
lst = [['Alice', 25], ['Bob', 30]]
df = pd.DataFrame(lst, columns=['Name', 'Age'])
print(df)

    Name  Age
0  Alice   25
1    Bob   30

In [5]:
df.head()  	# First 5 rows

    Name  Age
0  Alice   25
1    Bob   30

In [6]:
df.tail()  	# Last 5 rows

    Name  Age
0  Alice   25
1    Bob   30

In [7]:
df.info()  	# Info about DataFrame

<class 'pandas.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    2 non-null      str
 1   Age     2 non-null      int64
dtypes: int64(1), str(1)
memory usage: 164.0 bytes

In [8]:
df.describe()  # Summary statistics

             Age
count   2.000000
mean   27.500000
std     3.535534
min    25.000000
25%    26.250000
50%    27.500000
75%    28.750000
max    30.000000

In [13]:
# Column selection
print(df['Name'])
print(df[['Name', 'Age']])

0    Alice
1      Bob
Name: Name, dtype: str
    Name  Age
0  Alice   25
1    Bob   30

In [17]:
# Row selection by label and position
print(df.loc[0])
print(df.iloc[1])

Name    Alice
Age        25
Name: 0, dtype: object
Name    Bob
Age      30
Name: 1, dtype: object

In [18]:
df[df['Age'] > 25]  # Rows where Age > 25

  Name  Age
1  Bob   30

In [19]:
df['Gender'] = ['F', 'M']  # Add new column

In [20]:
print(df)

    Name  Age Gender
0  Alice   25      F
1    Bob   30      M

In [21]:
df.drop('Age', axis=1, inplace=True)  # Remove column

In [22]:
print(df)

    Name Gender
0  Alice      F
1    Bob      M

In [23]:
df.isnull()

    Name  Gender
0  False   False
1  False   False

In [24]:
df.dropna()

    Name Gender
0  Alice      F
1    Bob      M

In [25]:
df.fillna(0)

    Name Gender
0  Alice      F
1    Bob      M

In [28]:
df['Age'] = [25,30]

In [29]:
df.groupby('Gender')['Age'].mean()

Gender
F    25.0
M    30.0
Name: Age, dtype: float64

In [31]:
df1 = pd.DataFrame({
    'key': [1, 2, 3],
    'Name': ['Ali', 'Sara', 'John']
})

In [32]:
df2 = pd.DataFrame({
    'key': [1, 2, 3],
    'Age': [20, 21, 22]
})

In [33]:
# Merge two DataFrames
pd.merge(df1, df2, on='key')

   key  Name  Age
0    1   Ali   20
1    2  Sara   21
2    3  John   22

In [35]:
# Join by index
df1.set_index('key').join(
    df2.set_index('key')
)

     Name  Age
key
1     Ali   20
2    Sara   21
3    John   22

In [37]:
# Write CSV
df.to_csv('data.csv', index=False)

In [39]:
# Read CSV
df = pd.read_csv('data.csv')
print(df)

    Name Gender  Age
0  Alice      F   25
1    Bob      M   30

In [40]:
df.sort_values('Age')

    Name Gender  Age
0  Alice      F   25
1    Bob      M   30

In [41]:
df['Age'].apply(lambda x: x + 1)

0    26
1    31
Name: Age, dtype: int64

In [42]:
df['Name'].unique()

<StringArray>
['Alice', 'Bob']
Length: 2, dtype: str

In [43]:
df['Age'].value_counts()

Age
25    1
30    1
Name: count, dtype: int64